GET https://localhost:8080/api/user
Authorization: Bearer eyJyZWdEYXRlIjoxNjQ4NDY5NjEyNTM1LCJ0eXAiOiJBQ0NFU1NfVE9LRU4iLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyNCIsIm5hbWUiOiLsnbTrpoQiLCJpZCI6InVzZXI0IiwiZXhwIjoxNjQ4NDcwMjEyfQ.eS65ECOLRJCXGzshbo3UWfkeTv8tdFhZkC5V2KbPY9EOmvnz2jZk-S_OyXVKekmSHqVViqZpRwixLoOE2H6cyg

