
POST https://localhost:8080/api/product/option
Content-Type: application/json

{
  "name": "323",
  "proId": 2,
  "detailOptionList": []
}

###
POST https://localhost:8080/api/product/createDetailOption
Content-Type: application/json

{
  "name": "String",
  "price": 4000,
  "optionId": 7
}
###

DELETE https://localhost:8080/api/product/option/5

###
PATCH https://localhost:8080/api/product/option
Content-Type: application/json

{
  "id": 6,
  "name": "2232",
  "proId": 2,
  "detailOptionList": []
}