POST https://localhost:8080/api/company
Content-Type: multipart/form-data

 "json":"{
  "companyNumber":"123123",
  "openDate":"2022-12-12",
  "category":"MART",
  "name":"String",
  "mail":"String",
  "phone":"String",
  "member":{
    "id":1
  }
}"