POST https://localhost:8080/api/product/createOption
Content-Type: application/json

{
  "name": "sad",
  "proId": 3
}

###
POST https://localhost:8080/api/product/createDetailOption
Content-Type: application/json

{
  "name": "String",
  "price": 4000,
  "optionId": 7
}
###

DELETE https://localhost:8080/api/product/deleteOption/17